services:
  drone-vc-m:
    build: .
    environment:
      API_ID: $API_ID  
      API_HASH: $API_HASH  
      BOT_TOKEN: $BOT_TOKEN 
      DB_URI: $DB_URI
      USER_SESSION: $USER_SESSION
    resources:
      cpu: 1000m
